name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run linting (if configured)
      run: pnpm run lint
      continue-on-error: true
      
    - name: Build SvelteKit app
      run: pnpm run build
      
    - name: Debug - Verify build contents
      run: |
        echo "Build directory contents:"
        ls -la build/
        echo "First 20 lines of build/index.html:"
        head -20 build/index.html
        echo "Looking for your app content:"
        grep -i "portfolio\|welcome" build/index.html || echo "App content not found"
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4